### ISSUE TITLE
Typo busybox / nginx 

### ISSUE THREAD

**Issue by tpoindessous** [scraly/understanding-kubernetes-in-a-visual-way#7]
Hello

in v2.0.0 of the book, page 78, you wrote « with busybox image » and the code uses « nginx ». 

Thanks for your work !
Do you have , please , a ERRATUM file about corrections made in each release of the book ?  ( only corrections , not additional pages , I will buy new version of the book in few months !)

**Comment by scraly** [comment]
Hi Thomas,
currently the latest version of the published book is version 2.0.3 and this issue is already solved :)  

<img width="736" alt="image" src="https://github.com/scraly/understanding-kubernetes-in-a-visual-way/assets/2543381/7a07d65c-11b2-47cd-87ed-0bf4eb859352">

If you bought the book on GumRoad, you can have for free the updates with all the fixes/corrections and new pages/features/updates :).

If you will buy the book in [paperback](https://www.amazon.fr/dp/B0BB619188/ref=cm_cr_arp_d_product_top?ie=UTF8), the corections are already done.

FYI, I update for each version of Kubernetes all the editions of the book (PDF and then paperback).
It's a lot of work every month, personal work.

If you want to see what is the latest version of the book, the tips is to go to [GumRoad](https://aurelievache.gumroad.com/) page:
<img width="1195" alt="image" src="https://github.com/scraly/understanding-kubernetes-in-a-visual-way/assets/2543381/8ba0e748-0ea9-4693-ac71-1c7ec454e6f0">
At the right you can see the version 2.0.3.
